include:
    # Metadata shared my many jobs
    - local: .gitlab/rules.yml
    - local: .gitlab/artifacts.yml
    - local: .gitlab/release.yml

    # OS builds.
    - local: .gitlab/os-linux.yml
    - local: .gitlab/os-macos.yml
    - local: .gitlab/os-windows.yml

stages:
    - build-test
    - upload

################################################################################
# Job declarations
#
# Each job must pull in each of the following keys:
#
#   - a "base image"
#   - a build script
#   - tags for the jobs
#     - already provided for upload and CI update jobs
#   - rules for when to run the job
#
# Additionally, jobs may also contain:
#
#   - artifacts
#   - dependency/needs jobs for required jobs
################################################################################

# Release jobs

build-test:source:
    extends:
        - .create_source_archives
        - .release_artifacts
        - .linux_builder_tags
        - .run_automatically

upload:source:
    extends:
        - .upload_job
        - .release_only
    needs:
        - build-test:source
        # Ensure all builds and tests pass.
        - build-test:fedora36
        - build-test:fedora36-replay
        - build-test:fedora36-asan
        - build-test:fedora36-ubsan
        - build-test:fedora36-asan-mpi-replay
        - build-test:fedora36-mpi-replay-ubsan
        - build-test:macos-arm64-replay
        - build-test:macos-x86_64-replay
        - build-test:windows-vs2022-mpi-replay
        - build-test:windows-vs2022-replay
    dependencies:
        - build-test:source
    variables:
        UPLOAD_FILES: catalyst-*

# Linux

build-test:fedora36:
    extends:
        - .fedora36_basic
        - .cmake_build_linux
        - .cmake_build_artifacts
        - .linux_builder_tags
        - .run_automatically

build-test:fedora36-replay:
    extends:
        - .fedora36_replay
        - .cmake_build_linux
        - .cmake_build_artifacts
        - .linux_builder_tags
        - .run_automatically

build-test:fedora36-mpi-replay:
    extends:
        - .fedora36_mpi_replay
        - .cmake_build_linux
        - .cmake_build_artifacts
        - .linux_builder_tags
        - .run_automatically

build-test:fedora36-asan:
    extends:
        - .fedora36_asan
        - .cmake_memcheck_linux
        - .cmake_build_artifacts
        - .linux_sanitizer_tags
        - .run_automatically

build-test:fedora36-ubsan:
    extends:
        - .fedora36_ubsan
        - .cmake_memcheck_linux
        - .cmake_build_artifacts
        - .linux_sanitizer_tags
        - .run_automatically

build-test:fedora36-asan-mpi-replay:
    extends:
        - .fedora36_asan_mpi_replay
        - .cmake_memcheck_linux
        - .cmake_build_artifacts
        - .linux_sanitizer_tags
        - .run_automatically

build-test:fedora36-mpi-replay-ubsan:
    extends:
        - .fedora36_mpi_replay_ubsan
        - .cmake_memcheck_linux
        - .cmake_build_artifacts
        - .linux_sanitizer_tags
        - .run_automatically

# macOS

build-test:macos-arm64-replay:
    extends:
        - .macos_arm64_replay
        - .cmake_build_macos
        - .cmake_build_artifacts
        - .macos_arm64_builder_tags
        - .run_automatically

build-test:macos-x86_64-replay:
    extends:
        - .macos_x86_64_replay
        - .cmake_build_macos
        - .cmake_build_artifacts
        - .macos_x86_64_builder_tags
        - .run_automatically

# Windows

build-test:windows-vs2022-mpi-replay:
    extends:
        - .windows_vs2022_mpi_replay
        - .cmake_build_windows
        - .cmake_build_artifacts
        - .windows_mpi_builder_tags
        - .run_automatically

build-test:windows-vs2022-replay:
    extends:
        - .windows_vs2022_replay
        - .cmake_build_windows
        - .cmake_build_artifacts
        - .windows_builder_tags
        - .run_automatically
