include:
    # Metadata shared my many jobs
    - local: .gitlab/rules.yml
    - local: .gitlab/artifacts.yml

    # OS builds.
    - local: .gitlab/os-linux.yml
    - local: .gitlab/os-macos.yml
    - local: .gitlab/os-windows.yml

stages:
    - build-test

################################################################################
# Job declarations
#
# Each job must pull in each of the following keys:
#
#   - a "base image"
#   - a build script
#   - tags for the jobs
#     - already provided for upload and CI update jobs
#   - rules for when to run the job
#
# Additionally, jobs may also contain:
#
#   - artifacts
#   - dependency/needs jobs for required jobs
################################################################################

# Linux

build-test:fedora33:
    extends:
        - .fedora33_basic
        - .cmake_build_linux
        - .cmake_build_artifacts
        - .linux_builder_tags
        - .run_automatically

build-test:fedora33-replay:
    extends:
        - .fedora33_replay
        - .cmake_build_linux
        - .cmake_build_artifacts
        - .linux_builder_tags
        - .run_automatically

build-test:fedora33-mpi-replay:
    extends:
        - .fedora33_mpi_replay
        - .cmake_build_linux
        - .cmake_build_artifacts
        - .linux_builder_tags
        - .run_automatically

# macOS

build-test:macos-arm64-replay:
    extends:
        - .macos_arm64_replay
        - .cmake_build_macos
        - .cmake_build_artifacts
        - .macos_arm64_builder_tags
        - .run_automatically

build-test:macos-x86_64-replay:
    extends:
        - .macos_x86_64_replay
        - .cmake_build_macos
        - .cmake_build_artifacts
        - .macos_x86_64_builder_tags
        - .run_automatically

# Windows

build-test:windows-vs2019-mpi-replay:
    extends:
        - .windows_vs2019_mpi_replay
        - .cmake_build_windows
        - .cmake_build_artifacts
        - .windows_builder_tags
        - .run_automatically

build-test:windows-vs2019-replay:
    extends:
        - .windows_vs2019_replay
        - .cmake_build_windows
        - .cmake_build_artifacts
        - .windows_mpi_builder_tags
        - .run_automatically
